{% set name = "xalan-c" %}
{% set version = "1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # xalan lib uses <major>_<minor> in links instead of <major>.<minor>
  url: https://github.com/apache/xalan-c/archive/Xalan-C_{{ version|replace(".","_") }}_0.tar.gz
  sha256: f3d4f23af7f7914259f2f5dbd9cc1450d3ebe0b8c8163fd50fcac4a39c63fccd

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [not 'osx-arm64']
    - clang >=16,<17  # ['osx-arm64']
  
  host:
    - xerces-c >=3

test:
  commands:
    - test -f ${PREFIX}/include/xalanc/XPathCAPI/XPathCAPI.h
    - test -f ${PREFIX}/include/xalanc/XPath/XPath.hpp
    - test -f ${PREFIX}/lib/libxalan-c${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libxalanMsg${SHLIB_EXT}
    - test -f ${PREFIX}/bin/Xalan

about:
  home: https://github.com/simplejson/simplejson
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Command line program to transform XML documents using a stylesheet that conforms to XSLT 1.0 standards.'

  description: |
    The Apache Xalan C/C++ Project provides a library and a 
    command line program to transform XML documents using a
    stylesheet that conforms to XSLT 1.0 standards.

    The source package contains all the code to create the library,
    a command line transform utility and the documentation.

    The documentation packages provide pre-built html documents
    for web browser use.

    Binary prebuilt packages are available for some platforms.
    We could use help providing packages for more platforms.

    Xalan is a project of the Apache Software Foundation.

  doc_url: https://xalan.apache.org/xalan-c/index.html
  dev_url: https://github.com/apache/xalan-c

extra:
  recipe-maintainers:
    - andrewannex
    - kelvinrr

